(() => {
  const $ = id => document.getElementById(id), els = ['focus','ap','grain','density','smooth'].reduce((o,id)=>(o[id]=$(id),o),{});
  const cv=$('spec'), g=cv.getContext('2d'), status=$('status'); let ctx,node,bytes,sample,sr,duration=0,analysis,rays=[],recording=false,rec=[],rafStarted=false;
  const worker=new Worker('spectral-worker.js');
  const meter=(id,v)=>$(id).textContent=v;
  function updateLabels(){ $('focusV').value=(+els.focus.value*duration||0).toFixed(2)+' s'; $('apV').value=(+els.ap.value*duration||0).toFixed(2)+' s'; $('grainV').value=els.grain.value+' ms'; $('densityV').value=els.density.value+'/s'; $('smoothV').value=els.smooth.value; }
  async function engine(){ if(ctx)return; ctx=new AudioContext(); bytes=await (await fetch('raydrone.wasm',{cache:'no-store'})).arrayBuffer(); await ctx.audioWorklet.addModule('processor.js'); node=new AudioWorkletNode(ctx,'raydrone',{numberOfInputs:0,numberOfOutputs:1,outputChannelCount:[2],processorOptions:{wasmBytes:bytes}}); node.connect(ctx.destination); node.port.onmessage=({data:d})=>{ if(d.type==='rays'){rays.push(...d.offsets);if(rays.length>100)rays.splice(0,rays.length-100)} if(d.perf){meter('cpu',d.perf.cpu<0?'—':d.perf.cpu.toFixed(1)+'%');meter('voices',d.perf.voices);meter('gps',d.perf.spawnsPerSec.toFixed(0))} if(d.type==='recdata'){if(d.l.length)rec.push([d.l,d.r]);if(d.done){downloadWav();recording=false;$('export').textContent='Exportar WAV'}}}; const win=new Float32Array(2048);for(let i=0;i<win.length;i++)win[i]=.5-.5*Math.cos(2*Math.PI*i/(win.length-1));node.port.postMessage({type:'window',data:win}); }
  function send(){if(!node||!sample)return;const focus=+els.focus.value*duration,ap=+els.ap.value*duration,mode=+$('mode').value;node.port.postMessage({type:'params',focus,aperture:ap,grainMs:+els.grain.value,grainRate:+els.density.value,gain:.28,master:1});node.port.postMessage({type:'mode',value:mode});node.port.postMessage({type:'smart',on:mode===3?1:0});if(analysis)node.port.postMessage({type:'spectral',q:analysis.q,p:analysis.p,cdf:analysis.cdf,unbiased:$('bias').value==='unbiased',qFloor:1e-6});}
  async function load(file){try{await engine();const b=await file.arrayBuffer();const decoded=await ctx.decodeAudioData(b);sr=decoded.sampleRate;duration=decoded.duration;sample=new Float32Array(decoded.length);for(let c=0;c<decoded.numberOfChannels;c++){const ch=decoded.getChannelData(c);for(let i=0;i<sample.length;i++)sample[i]+=ch[i]/decoded.numberOfChannels}node.port.postMessage({type:'sample',data:sample,sampleRate:sr});['original','drone','spectral','export'].forEach(id=>$(id).disabled=false);updateLabels();analyse();status.textContent=`${file.name} · ${duration.toFixed(2)} s · ${sr} Hz`}catch(e){status.textContent='No se pudo decodificar el archivo. Prueba WAV, MP3 o AAC.';console.error(e)}}
  function analyse(){if(!sample)return;status.textContent='Analizando STFT en Worker…';worker.postMessage({samples:sample.buffer.slice(0),sampleRate:sr,fftSize:+$('fft').value,hopSize:+$('hop').value,minHz:+$('min').value,maxHz:+$('max').value,smoothing:+els.smooth.value,focus:+els.focus.value,aperture:+els.ap.value},[])}
  worker.onmessage=({data:d})=>{analysis=d;meter('analysis',d.analysisMs.toFixed(1)+' ms');meter('frames',d.frames);meter('memory',((d.image.byteLength+d.q.byteLength+d.cdf.byteLength)/1048576).toFixed(2)+' MB');meter('latency',((+$('fft').value/sr)*1000).toFixed(1)+' ms');send();status.textContent='Mapa spectral listo · q(τ) está condicionada por foco y apertura.';if(!rafStarted){rafStarted=true;draw()}};
  worker.onerror=()=>{status.textContent='El análisis spectral falló. Reduce FFT/Hop o carga un audio más corto.'};
  function draw(){const w=cv.width,h=cv.height;g.fillStyle='#030403';g.fillRect(0,0,w,h);if(!analysis){setTimeout(draw,250);return}const {frames,bins,image,q}=analysis;const iw=Math.max(1,Math.floor(w/frames)),ih=Math.max(1,Math.floor(h/bins));for(let x=0;x<frames;x++)for(let y=0;y<bins;y++){const v=image[x*bins+y];g.fillStyle=`rgb(${Math.floor(v*.95)},${Math.floor(v*.42)},${Math.floor(v*.08)})`;g.fillRect(x*w/frames,y*h/bins,iw+1,ih+1)}g.beginPath();for(let i=0;i<frames;i++){const x=i*w/(frames-1),y=h-10-q[i]*frames*h*.65;if(i)g.lineTo(x,y);else g.moveTo(x,y)}g.strokeStyle='#ffd447';g.lineWidth=2;g.stroke();const f=+els.focus.value,a=+els.ap.value;g.fillStyle='rgba(255,59,24,.16)';g.fillRect(Math.max(0,(f-a)*w),0,Math.min(w,(f+a)*w)-Math.max(0,(f-a)*w),h);g.strokeStyle='#ff3b18';g.beginPath();g.moveTo(f*w,0);g.lineTo(f*w,h);g.stroke();g.strokeStyle='rgba(255,248,232,.6)';for(const r of rays){const x=r/duration*w;g.beginPath();g.moveTo(x,h);g.lineTo(x,h-20);g.stroke()}setTimeout(draw,250) }
  function play(kind){if(kind==='spectral'&&!analysis){status.textContent='Espera a que termine el análisis STFT antes de escuchar Spectral Guide.';return}send();node.port.postMessage({type:'direct',on:0,offsetSec:0});if(kind==='original'){node.port.postMessage({type:'params',focus:0,aperture:0,grainMs:180,grainRate:0,gain:.3,master:1});node.port.postMessage({type:'direct',on:1,offsetSec:0})}else{if(kind==='spectral')$('mode').value='4';else if(+$('mode').value>2)$('mode').value='1';send()}ctx.resume();status.textContent=kind==='original'?'Original reproduciéndose.':kind==='spectral'?'Spectral Guide · foco/apertura + energía de banda.':'RayDrone temporal reproduciéndose.'}
  $('file').onchange=e=>e.target.files[0]&&load(e.target.files[0]);$('original').onclick=()=>play('original');$('drone').onclick=()=>play('drone');$('spectral').onclick=()=>play('spectral');$('stop').onclick=()=>{if(node){node.port.postMessage({type:'direct',on:0,offsetSec:0});node.port.postMessage({type:'params',focus:0,aperture:0,grainMs:180,grainRate:0,gain:.3,master:1})}status.textContent='Detenido.'};$('export').onclick=()=>{if(!node)return;if(!recording){rec=[];recording=true;node.port.postMessage({type:'record',on:true});$('export').textContent='Detener y descargar'}else node.port.postMessage({type:'record',on:false})};
  ['fft','hop','min','max'].forEach(id=>$(id).onchange=analyse);['focus','ap','grain','density','smooth','mode','bias'].forEach(id=>$(id).oninput=()=>{updateLabels();send();if(['focus','ap','smooth'].includes(id))analyse()});document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{const p=b.dataset.p;if(p==='deep'){els.focus.value=.45;els.ap.value=.18;els.density.value=110;$('min').value=70;$('max').value=1600;els.smooth.value=.7}else if(p==='mist'){els.ap.value=.7;els.density.value=300;$('min').value=50;$('max').value=9000;els.smooth.value=.55}else{els.ap.value=.35;els.grain.value=75;els.density.value=240;els.smooth.value=.15}updateLabels();analyse()});
  function downloadWav(){let n=0;for(const [l] of rec)n+=l.length;const b=new ArrayBuffer(44+n*4),v=new DataView(b);const s=(o,x)=>{for(let i=0;i<x.length;i++)v.setUint8(o+i,x.charCodeAt(i))};s(0,'RIFF');v.setUint32(4,36+n*4,true);s(8,'WAVE');s(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,2,true);v.setUint32(24,ctx.sampleRate,true);v.setUint32(28,ctx.sampleRate*4,true);v.setUint16(32,4,true);v.setUint16(34,16,true);s(36,'data');v.setUint32(40,n*4,true);let o=44;for(const [l,r]of rec)for(let i=0;i<l.length;i++){v.setInt16(o,Math.max(-1,Math.min(1,l[i]))*32767,true);v.setInt16(o+2,Math.max(-1,Math.min(1,r[i]))*32767,true);o+=4}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([b],{type:'audio/wav'}));a.download='raydrone-spectral.wav';a.click();URL.revokeObjectURL(a.href)}updateLabels();draw();
})();
